# Generated by Django 3.2.9 on 2021-11-26 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50)),
                ('date', models.DateTimeField(verbose_name='date_time')),
                ('text', models.TextField(max_length=1000)),
            ],
        ),
    ]
